export const nets = {
  gnd: "net.GND",
  vbus: "net.VBUS_5V",
  v3v3: "net.V3_3",
  usbDp: "net.USB_DP",
  usbDm: "net.USB_DM",
  audioMclk: "net.AUDIO_MCLK",
  audioBclk: "net.AUDIO_BCLK",
  audioLrck: "net.AUDIO_LRCK",
  audioData: "net.AUDIO_DATA",
  oledScl: "net.OLED_SCL",
  oledSda: "net.OLED_SDA",
  ledData: "net.LED_DATA",
  ledSrclk: "net.LED_SRCLK",
  ledLatch: "net.LED_LATCH",
  ledOe: "net.LED_OE",
  boot0: "net.BOOT0",
  reset: "net.NRST",
} as const
