export const nets = {
	gnd: "net.GND",
	vbus: "net.VBUS_5V",
	v3v3: "net.V3_3",
	usbDp: "net.USB_DP",
	usbDm: "net.USB_DM",
	audioLeft: "net.AUDIO_LEFT_ADC",
	audioRight: "net.AUDIO_RIGHT_ADC",
	ledData: "net.LED_DATA",
	ledSrclk: "net.LED_SRCLK",
	ledLatch: "net.LED_LATCH",
	ledOe: "net.LED_OE",
	boot0: "net.BOOT0",
	reset: "net.NRST",
} as const;
